/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Todo一覧を取得する */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @example 1 */
                                id: number;
                                /** @example 買い物 */
                                title: string;
                                /** @example 牛乳を買う */
                                description: string;
                                /** @example false */
                                completed: boolean;
                                /** @example 2024-01-01T00:00:00.000Z */
                                createdAt: string;
                            }[];
                            statusCode: number;
                        };
                    };
                };
                /** @description 取得失敗 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            statusCode: number;
                            details?: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description TodoをIDで取得する */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @example 1 */
                                id: number;
                                /** @example 買い物 */
                                title: string;
                                /** @example 牛乳を買う */
                                description: string;
                                /** @example false */
                                completed: boolean;
                                /** @example 2024-01-01T00:00:00.000Z */
                                createdAt: string;
                            };
                            statusCode: number;
                        };
                    };
                };
                /** @description Todoが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            statusCode: number;
                            details?: unknown;
                        };
                    };
                };
                /** @description 取得失敗 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            statusCode: number;
                            details?: unknown;
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title: string;
                        description?: string;
                        completed: boolean;
                    };
                };
            };
            responses: {
                /** @description Todoを更新する */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @example 1 */
                                id: number;
                                /** @example 買い物 */
                                title: string;
                                /** @example 牛乳を買う */
                                description: string;
                                /** @example false */
                                completed: boolean;
                                /** @example 2024-01-01T00:00:00.000Z */
                                createdAt: string;
                            };
                            statusCode: number;
                        };
                    };
                };
                /** @description Todoが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            statusCode: number;
                            details?: unknown;
                        };
                    };
                };
                /** @description 更新失敗 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            statusCode: number;
                            details?: unknown;
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Todoを削除する */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: number;
                            };
                            statusCode: number;
                        };
                    };
                };
                /** @description Todoが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            statusCode: number;
                            details?: unknown;
                        };
                    };
                };
                /** @description 削除失敗 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            statusCode: number;
                            details?: unknown;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title: string;
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Todoを作成する */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @example 1 */
                                id: number;
                                /** @example 買い物 */
                                title: string;
                                /** @example 牛乳を買う */
                                description: string;
                                /** @example false */
                                completed: boolean;
                                /** @example 2024-01-01T00:00:00.000Z */
                                createdAt: string;
                            };
                            statusCode: number;
                        };
                    };
                };
                /** @description 作成失敗 */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            statusCode: number;
                            details?: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
